/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package tasks

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'gradle_dependency_graph_plugin.greeting' plugin.
 */
public class Gradle_dependency_graph_pluginPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("gradle_dependency_graph_plugin.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
